### PR TITLE
More Zephyr fixes

### PR DESCRIPTION
**Pull request by Frauschi**
Five independent Zephyr fixes and one benchmark fix, one per commit. Items 1-3 were the original PR; 4-6 were added since.

**1. Call Zephyr's clock API instead of remapping the POSIX names.** `wc_port.h` guarded a `sys_clock_gettime()`/`sys_clock_settime()` remap with `#ifndef CLOCK_REALTIME`, but picolibc and newlib both define `CLOCK_REALTIME` themselves. The guard was always false, so `z_time()` called `clock_gettime()`, which exists only when the application enables `CONFIG_POSIX_TIMERS`:

```
test.c:3657:9: error: implicit declaration of function 'clock_settime'
```

Making the remap unconditional fixes that build but hands every consumer a library-wide rewrite of two POSIX names, the same shape as item 3 below: `wc_port.h` is reached from every wolfCrypt header, so an application calling `clock_gettime()` would silently get `sys_clock_gettime()`, which reports failure as a negative errno instead of `-1` plus `errno`.

So the macros are gone and the three places that need the Zephyr call name it - `z_time()`, the wolfCrypt test's dummy wallclock, and the threaded TLS sample - each keeping the POSIX call for Zephyr versions without `SYS_CLOCK_REALTIME`. `sys_clock_gettime()` is core Zephyr rather than POSIX and is always present; no new public macro is needed, since `<zephyr/kernel.h>` already pulls in `sys/clock.h` and `settings.h` already includes `kernel.h`.

**2. Put the wolfSSL interface library on `zephyr_interface`.** `target_link_libraries(wolfSSL INTERFACE zephyr_interface)` links the two the wrong way round, so wolfSSL's `WOLFSSL_USER_SETTINGS` reached nothing. Any Zephyr library including a wolfSSL header had to remember `zephyr_library_link_libraries(wolfSSL)`; one that forgets still compiles, then disagrees with libwolfssl about structure layout at run time. `zephyr_link_libraries(wolfSSL)` is what the mbedTLS module does, and it only adds: comparing every entry in `compile_commands.json` both ways, no translation unit loses a define or include path, 175 gain them, and the image has the same size and symbols.

**3. Stop redefining the POSIX socket names library-wide.** Since Zephyr 4.1 removed `CONFIG_NET_SOCKETS_POSIX_NAMES`, `settings.h` defined 14 socket names as object-like macros. `settings.h` reaches every wolfSSL header, so those rewrite any matching token anywhere, including structure members: Zephyr's `struct socket_op_vtable` declares `bind`, `connect`, `listen`, `accept`, `shutdown` and more, and whether a file compiles depends on its include order.

```c
#include <zephyr/net/socket.h>
#include <wolfssl/ssl.h>
static const struct socket_op_vtable vt = { .bind = my_bind };

error: 'const struct socket_op_vtable' has no member named 'zsock_bind'
```

The compiler then falls back to positional initialization, installing the handler in the wrong slot. Zephyr's own TLS socket layer carries a block of `#undef`s to defuse this.

wolfSSL now calls Zephyr's API by name. `send`/`recv`, `sendto`/`recvfrom`, `socket`/`accept`, `close` and `inet_pton`/`inet_ntop` already had wrappers that only needed a Zephyr value; `bind`, `connect`, `listen`, `getsockopt`, `setsockopt` and `getpeername` get new `XSOCKET_*` macros in `wolfio.h`. They default to the BSD names, so every other port preprocesses exactly as before. `wolfssl/test.h` keeps a remapping of its own, placed after its system includes and function-like so it cannot rewrite a structure member.

`zsock_` is the only spelling that works in every configuration from 4.4 on, since the POSIX aliases need `CONFIG_NET_NAMESPACE_COMPAT_MODE`, which restores types and constants but never function names.

**4. Add Kconfig options for OCSP and OCSP stapling.** Nothing in the module exposed `HAVE_OCSP` or the certificate status request extension, so a Kconfig-driven build had no way to ask a TLS server to staple an OCSP response for its own certificate. `WOLFSSL_OCSP` and `WOLFSSL_OCSP_STAPLING` both default to off, so no existing configuration changes.

**5. Add a Kconfig option for the crypto callback interface.** `WOLF_CRYPTO_CB` reached a Kconfig-driven build only through wolfTPM, so an application with a crypto device of its own had no way to enable the callback interface, and no way to reach `WOLF_PRIVATE_KEY_ID` with it - which is what lets a TLS private key stay on that device rather than sit in the application's memory.

A port that brings its own device should keep defining `WOLF_CRYPTO_CB` from its own option rather than selecting this one. A `select` also reaches a settings-file build, and there the settings file is authoritative over anything that changes structure layouts. wolfTPM's existing define in `user_settings.h` is now `#ifndef`-guarded so the two cannot collide.

**6. Label the GMAC benchmark rows by the device that ran them.** Not Zephyr-specific, but found while benchmarking a Zephyr crypto-callback port, and a one-line fix. `bench_gmac_internal()` passed a literal `0` as `useDeviceID` to `bench_stats_sym_finish()`, so with `BENCH_DEVID` defined both the software and the hardware run printed `SW`, and `bench_stats_add()` merged them into one entry because it keys on that value too. On an accelerator where GMAC goes from 146 KiB/s to 8.7 MiB/s the mislabelling is easy to spot, but the table said the two were the same measurement.

### CODE REVIEW

File: wolfssl/wolfcrypt/wc_port.h [hunk 1]
```diff
@@ -1727,13 +1727,18 @@ WOLFSSL_ABI WOLFSSL_API int wolfCrypt_Cleanup(void);
...
-        #ifdef SYS_CLOCK_REALTIME
+    /* Keyed on SYS_CLOCK_REALTIME: picolibc and newlib define CLOCK_REALTIME
+     * themselves, but only Zephyr's POSIX layer defines clock_gettime(). */
+    #ifdef SYS_CLOCK_REALTIME
+        #ifndef CLOCK_REALTIME
             #define CLOCK_REALTIME  SYS_CLOCK_REALTIME
-            #define clock_gettime   sys_clock_gettime
-            #define clock_settime   sys_clock_settime
         #endif
+        #define clock_gettime   sys_clock_gettime
```
[the remark this answers is not in the document]
Comment (Frauschi) [reply wolfssl/wolfcrypt/wc_port.h]: Good catch, fixed in 027e59f.

You're right, and it's the same problem the third commit in this PR exists to remove - I fixed the guard without noticing I was making the hijack unconditional in the process.

The macros are gone. `z_time()` calls `sys_clock_gettime(SYS_CLOCK_REALTIME, &ts)` directly, and the two remaining POSIX callers under `WOLFSSL_ZEPHYR` (the dummy wallclock in `wolfcrypt/test/test.c` and in `zephyr/samples/wolfssl_tls_thread`) call `sys_clock_settime()` the same way. Each site keeps an `#ifdef SYS_CLOCK_REALTIME` fallback to the POSIX call for Zephyr older than `sys_clock_gettime()`. No new public macro: `<zephyr/kernel.h>` pulls in `sys/clock.h` via `kernel_includes.h`, and `settings.h` already includes `kernel.h`, so the names are in scope everywhere they are needed.

Verified by preprocessing a TU that includes `<wolfssl/ssl.h>` with the real build flags and dumping the macro table - `clock_gettime` and `clock_settime` are no longer defined, and the only `CLOCK_REALTIME` left is picolibc's own. The six wolfSSL Zephyr sample scenarios pass on qemu_x86, none of which enable `CONFIG_POSIX_TIMERS`.

**Comment by Frauschi** [comment]
Jenkins retest this please

**Comment by Frauschi** [comment]
Jenkins retest this please

**Comment by Frauschi** [comment]
Jenkins retest this please

**Comment by Frauschi** [comment]
This should be merged after #11401.

**Review by JacobBarthelmeh — APPROVED** [review]
