### PR TITLE
Fix for SP math with `RSA_LOW_MEM` (ARM only)

### PR DESCRIPTION
**Pull request by dgarske**
Broken in PR #2892.

### CODE REVIEW

**Comment by danielinux** [comment]
This fixes a compile error in one of the test cases of wolfboot with wolfSSL v4.4.0. With the option `SIGN=RSA2048` wolfboot compiles with SP_MATH, assembly optimizations for cortex-M and RSA_LOW_MEM.

Before this fix:

```
wolfboot $  make SIGN=RSA2048 
[CC-ARM] lib/wolfssl/wolfcrypt/src/sp_cortexm.o
lib/wolfssl/wolfcrypt/src/sp_cortexm.c:4126:6: error: expected identifier or '(' before 'void'
     (void)pm;
      ^~~~
 [ more similar errors ]
```
due to missing function header at wolfcrypt/src/sp_cortexm.c:4120.

Using this PR everything compiles fine again.
