### PR TITLE
Fixes for PIC32MZ

### PR DESCRIPTION
**Pull request by kojo1**
Fixes for PIC32MZ:
* Adds crypto HW support for AES Direct and AES CCM.
* Fixes to enable PIC32MZ hardware hashing where updates are cached via heap buffer and final performs single operations against hardware.
* Fix for benchmark with 1024-bit certs passing in wrong size for `wc_RsaPrivateDecrypt` when using `USE_CERT_BUFFERS_1024`.
* Fix to resolve missing `strncasecmp` for the Microchip XC32. Workaround to use case sensitive version instead. This error occurred when building with HAVE_ECC defined in Harmony with XC32.
* Cleanup of the PIC32MZ crypto and hashing hardware code. Replace `pic32mz-hash.c` with `pic32mz-crypt.c`
* Add user_settings.h for mplabx and mcapi examples.
* Sync up with Harmony changes for MCAPI.

### CODE REVIEW

**Comment by cconlon** [comment]
Using MPLABX 2.30 and XC32 1.40, compiling with only **MICROCHIP_PIC32** defined, the wolfssl.X project successfully builds.  The wolfcrypt_test.X and wolfcrypt_benchmark.X projects fail with the following errors:

**wolfcrypt_test.X**
```
nbproject/Makefile-default.mk:111: recipe for target 'build/default/production/_ext/1472/test_main.o' failed
../test_main.c:45:22: fatal error: plib.h: No such file or directory
     #include <plib.h>
```

**wolfrypt_benchmark.X**
```
C:\Program Files (x86)\Microchip\xc32\v1.40\bin\bin/xc32-ar.exe: creating dist/default/production/wolfssl.X.a
../benchmark_main.c:41:22: fatal error: plib.h: No such file or directory
     #include <plib.h>
```

Can you look into this?

Thanks,
Chris

**Comment by kojo1** [comment]
It should be included in "PIC32 Legacy Peripheral Libraries". This is for SYSTEMConfigPerformance(80000000);

Perhaps, we want to alter this macro than depending on legacy library.

Thanks.

Kojo

**Comment by cconlon** [comment]
It looks like the compiler defines "__XC32_VERSION" to match the compiler version.  For example, with XC32 1.34, __XC32_VERSION is defined to 1340.  For XC32 1.40, it is defined to 1400.  I think we should use these to exclude <plib.h> and SYSTEMConfigPerformance() on legacy compiler version.  Can you make that addition/change?

And, can you confirm that to compile with XC32 1.40, users must define both MICROCHIP_PIC32 and MICROCHIP_MPLAB_HARMONY, and be using a PIC32MZ board?

Thanks,
Chris

**Comment by cconlon** [comment]
Kojo,

Any updates on this pull request and taking advantage of __XC32_VERSION?

Thanks,
Chris

**Comment by kaleb-himes** [comment]
retest this please jenkins:

- had a new release cycle and been awhile since these were tested. Just double check again.

**Comment by kaleb-himes** [comment]
rebase with master and should be good to go.

**Comment by cconlon** [comment]
Assigning to David for additional testing.

**Comment by dgarske** [comment]
FYI: A rebased push was done for this PR.

Commit Notes:
Added PIC32MZ AES support for ECB (Direct) and AES CCM.
Added PIC32MZ support for DES/DES3 ECB.
Enabled PIC32MZ HW hashing for HMAC and PWDBASED.
Moved PIC32 crypto functions into ports/pic32/pic32mz-crypt.c.
Cleanup AES CCM to use separate functions for LTC.
Fix for AES to support other key sizes besides 128.
Fixes for building/using the WOLFSSL_PIC32MZ_HASH option.
General cleanup for AES with PIC32MZ. Fix baud calculation for PIC32MZ serial.

**Comment by dgarske** [comment]
@toddouska : I've completed the testing of the PIC32MZ changes and done a rebase -> squash merge -> force push. This PR is ready for another review.

**Comment by dgarske** [comment]
Rebased with latest master for Microchip. Completed testing and fixes for `wolfssl_tcp_client` example using PIC32MZ crypto acceleration (`WOLFSSL_PIC32MZ_CRYPT`). Up next is testing improvements for `WOLFSSL_PIC32MZ_HASH`.

**Comment by dgarske** [comment]
FYI: Pushed a rebase -> squash merge -> force push on this PR. To workaround the PIC32MZ hashing issue we've implemented caching of the updates and perform a single finish against hardware. The investigation of a hardware based update is still in progress. In case the hardware solution isn't ready in time this PR is ready using workaround.

**Comment by dgarske** [comment]
@toddouska : This is ready for final review. The effort to use hash updates directly against hardware is still in progress. This implementation to cache updates is the best solution to date.
