### ISSUE TITLE
[Bug]: Unable to compile DTLS1.3 SCTP support without TLS1.2

### ISSUE THREAD

**Issue by ghost** [wolfSSL/wolfssl#6974]
### Contact Details

nep-gh@packageloss.eu

### Version

v5.6.4-stable

### Description

commandline:
./configure --enable-dtls --enable-tls13 --enable-dtls13 --enable-sctp --disable-tlsv12

gcc version 13.2.0 (Ubuntu 13.2.0-4ubuntu3) 

/etc/os-release 
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo

### Reproduction steps

Configure as above, then plainly compiling with make

Removing the  --disable-tlsv12 gives a working build.

### Relevant log output

```shell
make
make -j13  all-recursive
make[1]: Entering directory '/home/nephele/proj/crazy-network-lib/wolfssl'
make[2]: Entering directory '/home/nephele/proj/crazy-network-lib/wolfssl'
make[2]: warning: -j13 forced in submake: resetting jobserver mode.
  CC       examples/sctp/sctp-server.o
  CC       examples/sctp/sctp-client.o
  CC       examples/sctp/sctp-server-dtls.o
  CC       examples/sctp/sctp-client-dtls.o
  CC       examples/pem/pem.o
  CC       examples/asn1/asn1.o
  CC       wolfcrypt/test/testsuite_testsuite_test-test.o
  CC       examples/echoclient/testsuite_testsuite_test-echoclient.o
  CC       examples/client/testsuite_testsuite_test-client.o
  CC       examples/echoserver/testsuite_testsuite_test-echoserver.o
  CC       examples/server/testsuite_testsuite_test-server.o
  CC       testsuite/testsuite_test-testsuite.o
  CC       tests/unit_test-unit.o
examples/sctp/sctp-client-dtls.c: In function ‘main’:
examples/sctp/sctp-server-dtls.c: In function ‘main’:
examples/sctp/sctp-client-dtls.c:75:40: error: implicit declaration of function ‘wolfDTLSv1_2_client_method’; did you mean ‘wolfDTLSv1_3_client_method’? [-Werror=implicit-function-declaration]
   75 |     WOLFSSL_CTX* ctx = wolfSSL_CTX_new(wolfDTLSv1_2_client_method());
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        wolfDTLSv1_3_client_method
examples/sctp/sctp-client-dtls.c:75:40: error: nested extern declaration of ‘wolfDTLSv1_2_client_method’ [-Werror=nested-externs]
examples/sctp/sctp-server-dtls.c:81:40: error: implicit declaration of function ‘wolfDTLSv1_2_server_method’; did you mean ‘wolfDTLSv1_3_server_method’? [-Werror=implicit-function-declaration]
   81 |     WOLFSSL_CTX* ctx = wolfSSL_CTX_new(wolfDTLSv1_2_server_method());
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        wolfDTLSv1_3_server_method
examples/sctp/sctp-server-dtls.c:81:40: error: nested extern declaration of ‘wolfDTLSv1_2_server_method’ [-Werror=nested-externs]
examples/sctp/sctp-client-dtls.c:75:40: error: passing argument 1 of ‘wolfSSL_CTX_new’ makes pointer from integer without a cast [-Werror=int-conversion]
   75 |     WOLFSSL_CTX* ctx = wolfSSL_CTX_new(wolfDTLSv1_2_client_method());
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        |
      |                                        int
examples/sctp/sctp-server-dtls.c:81:40: error: passing argument 1 of ‘wolfSSL_CTX_new’ makes pointer from integer without a cast [-Werror=int-conversion]
   81 |     WOLFSSL_CTX* ctx = wolfSSL_CTX_new(wolfDTLSv1_2_server_method());
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        |
      |                                        int
In file included from examples/sctp/sctp-server-dtls.c:27:
./wolfssl/ssl.h:1127:70: note: expected ‘WOLFSSL_METHOD *’ but argument is of type ‘int’
 1127 | WOLFSSL_ABI WOLFSSL_API WOLFSSL_CTX* wolfSSL_CTX_new(WOLFSSL_METHOD* method);
      |                                                      ~~~~~~~~~~~~~~~~^~~~~~
In file included from examples/sctp/sctp-client-dtls.c:28:
./wolfssl/ssl.h:1127:70: note: expected ‘WOLFSSL_METHOD *’ but argument is of type ‘int’
 1127 | WOLFSSL_ABI WOLFSSL_API WOLFSSL_CTX* wolfSSL_CTX_new(WOLFSSL_METHOD* method);
      |                                                      ~~~~~~~~~~~~~~~~^~~~~~
  CC       tests/unit_test-api.o
cc1: all warnings being treated as errors
make[2]: *** [Makefile:6310: examples/sctp/sctp-server-dtls.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
make[2]: *** [Makefile:6310: examples/sctp/sctp-client-dtls.o] Error 1
In file included from tests/api.c:152:
tests/api.c: In function ‘test_wolfSSL_dtls_set_mtu’:
tests/api.c:59428:41: error: implicit declaration of function ‘wolfDTLSv1_2_server_method’; did you mean ‘wolfDTLSv1_3_server_method’? [-Werror=implicit-function-declaration]
59428 |     ExpectNotNull(ctx = wolfSSL_CTX_new(wolfDTLSv1_2_server_method()));
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
./tests/unit.h:143:36: note: in definition of macro ‘Expect’
  143 |     if (_ret != TEST_FAIL) { if (!(test)) ExpFail(description, result);        \
      |                                    ^~~~
tests/api.c:59428:5: note: in expansion of macro ‘ExpectNotNull’
59428 |     ExpectNotNull(ctx = wolfSSL_CTX_new(wolfDTLSv1_2_server_method()));
      |     ^~~~~~~~~~~~~
tests/api.c:59428:41: error: nested extern declaration of ‘wolfDTLSv1_2_server_method’ [-Werror=nested-externs]
59428 |     ExpectNotNull(ctx = wolfSSL_CTX_new(wolfDTLSv1_2_server_method()));
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
./tests/unit.h:143:36: note: in definition of macro ‘Expect’
  143 |     if (_ret != TEST_FAIL) { if (!(test)) ExpFail(description, result);        \
      |                                    ^~~~
tests/api.c:59428:5: note: in expansion of macro ‘ExpectNotNull’
59428 |     ExpectNotNull(ctx = wolfSSL_CTX_new(wolfDTLSv1_2_server_method()));
      |     ^~~~~~~~~~~~~
tests/api.c:59428:41: error: passing argument 1 of ‘wolfSSL_CTX_new’ makes pointer from integer without a cast [-Werror=int-conversion]
59428 |     ExpectNotNull(ctx = wolfSSL_CTX_new(wolfDTLSv1_2_server_method()));
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         |
      |                                         int
./tests/unit.h:143:36: note: in definition of macro ‘Expect’
  143 |     if (_ret != TEST_FAIL) { if (!(test)) ExpFail(description, result);        \
      |                                    ^~~~
tests/api.c:59428:5: note: in expansion of macro ‘ExpectNotNull’
59428 |     ExpectNotNull(ctx = wolfSSL_CTX_new(wolfDTLSv1_2_server_method()));
      |     ^~~~~~~~~~~~~
In file included from tests/api.c:150:
./wolfssl/ssl.h:1127:70: note: expected ‘WOLFSSL_METHOD *’ but argument is of type ‘int’
 1127 | WOLFSSL_ABI WOLFSSL_API WOLFSSL_CTX* wolfSSL_CTX_new(WOLFSSL_METHOD* method);
      |                                                      ~~~~~~~~~~~~~~~~^~~~~~
tests/api.c: In function ‘test_wolfSSL_dtls_plaintext’:
tests/api.c:59548:10: error: ‘wolfDTLSv1_2_client_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_client_method’?
59548 |         {wolfDTLSv1_2_client_method, wolfDTLSv1_2_server_method,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |          wolfDTLSv1_3_client_method
tests/api.c:59548:10: note: each undeclared identifier is reported only once for each function it appears in
tests/api.c:59548:38: error: ‘wolfDTLSv1_2_server_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_server_method’?
59548 |         {wolfDTLSv1_2_client_method, wolfDTLSv1_2_server_method,
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      wolfDTLSv1_3_server_method
tests/api.c: In function ‘test_wolfSSL_dtls_fragments’:
tests/api.c:59701:10: error: ‘wolfDTLSv1_2_client_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_client_method’?
59701 |         {wolfDTLSv1_2_client_method, wolfDTLSv1_2_server_method,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |          wolfDTLSv1_3_client_method
tests/api.c:59701:38: error: ‘wolfDTLSv1_2_server_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_server_method’?
59701 |         {wolfDTLSv1_2_client_method, wolfDTLSv1_2_server_method,
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      wolfDTLSv1_3_server_method
tests/api.c: In function ‘_test_wolfSSL_ignore_alert_before_cookie’:
tests/api.c:59767:29: error: ‘wolfDTLSv1_2_client_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_client_method’?
59767 |         client_cbs.method = wolfDTLSv1_2_client_method;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                             wolfDTLSv1_3_client_method
tests/api.c:59768:29: error: ‘wolfDTLSv1_2_server_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_server_method’?
59768 |         server_cbs.method = wolfDTLSv1_2_server_method;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                             wolfDTLSv1_3_server_method
tests/api.c: In function ‘test_wolfSSL_dtls_bad_record’:
tests/api.c:59864:41: error: ‘wolfDTLSv1_2_client_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_client_method’?
59864 |     ret = _test_wolfSSL_dtls_bad_record(wolfDTLSv1_2_client_method,
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         wolfDTLSv1_3_client_method
tests/api.c:59865:9: error: ‘wolfDTLSv1_2_server_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_server_method’?
59865 |         wolfDTLSv1_2_server_method);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |         wolfDTLSv1_3_server_method
tests/api.c: In function ‘test_wolfSSL_dtls_stateless’:
tests/api.c:60358:10: error: ‘wolfDTLSv1_2_client_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_client_method’?
60358 |         {wolfDTLSv1_2_client_method, wolfDTLSv1_2_server_method,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |          wolfDTLSv1_3_client_method
tests/api.c:60358:38: error: ‘wolfDTLSv1_2_server_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_server_method’?
60358 |         {wolfDTLSv1_2_client_method, wolfDTLSv1_2_server_method,
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      wolfDTLSv1_3_server_method
tests/api.c: In function ‘test_dtls_ipv6_check’:
tests/api.c:65616:43: error: implicit declaration of function ‘wolfDTLSv1_2_client_method’; did you mean ‘wolfDTLSv1_3_client_method’? [-Werror=implicit-function-declaration]
65616 |     ExpectNotNull(ctx_c = wolfSSL_CTX_new(wolfDTLSv1_2_client_method()));
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
./tests/unit.h:143:36: note: in definition of macro ‘Expect’
  143 |     if (_ret != TEST_FAIL) { if (!(test)) ExpFail(description, result);        \
      |                                    ^~~~
tests/api.c:65616:5: note: in expansion of macro ‘ExpectNotNull’
65616 |     ExpectNotNull(ctx_c = wolfSSL_CTX_new(wolfDTLSv1_2_client_method()));
      |     ^~~~~~~~~~~~~
tests/api.c:65616:43: error: nested extern declaration of ‘wolfDTLSv1_2_client_method’ [-Werror=nested-externs]
65616 |     ExpectNotNull(ctx_c = wolfSSL_CTX_new(wolfDTLSv1_2_client_method()));
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
./tests/unit.h:143:36: note: in definition of macro ‘Expect’
  143 |     if (_ret != TEST_FAIL) { if (!(test)) ExpFail(description, result);        \
      |                                    ^~~~
tests/api.c:65616:5: note: in expansion of macro ‘ExpectNotNull’
65616 |     ExpectNotNull(ctx_c = wolfSSL_CTX_new(wolfDTLSv1_2_client_method()));
      |     ^~~~~~~~~~~~~
tests/api.c:65616:43: error: passing argument 1 of ‘wolfSSL_CTX_new’ makes pointer from integer without a cast [-Werror=int-conversion]
65616 |     ExpectNotNull(ctx_c = wolfSSL_CTX_new(wolfDTLSv1_2_client_method()));
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           |
      |                                           int
./tests/unit.h:143:36: note: in definition of macro ‘Expect’
  143 |     if (_ret != TEST_FAIL) { if (!(test)) ExpFail(description, result);        \
      |                                    ^~~~
tests/api.c:65616:5: note: in expansion of macro ‘ExpectNotNull’
65616 |     ExpectNotNull(ctx_c = wolfSSL_CTX_new(wolfDTLSv1_2_client_method()));
      |     ^~~~~~~~~~~~~
./wolfssl/ssl.h:1127:70: note: expected ‘WOLFSSL_METHOD *’ but argument is of type ‘int’
 1127 | WOLFSSL_ABI WOLFSSL_API WOLFSSL_CTX* wolfSSL_CTX_new(WOLFSSL_METHOD* method);
      |                                                      ~~~~~~~~~~~~~~~~^~~~~~
tests/api.c:65618:43: error: passing argument 1 of ‘wolfSSL_CTX_new’ makes pointer from integer without a cast [-Werror=int-conversion]
65618 |     ExpectNotNull(ctx_s = wolfSSL_CTX_new(wolfDTLSv1_2_server_method()));
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           |
      |                                           int
./tests/unit.h:143:36: note: in definition of macro ‘Expect’
  143 |     if (_ret != TEST_FAIL) { if (!(test)) ExpFail(description, result);        \
      |                                    ^~~~
tests/api.c:65618:5: note: in expansion of macro ‘ExpectNotNull’
65618 |     ExpectNotNull(ctx_s = wolfSSL_CTX_new(wolfDTLSv1_2_server_method()));
      |     ^~~~~~~~~~~~~
./wolfssl/ssl.h:1127:70: note: expected ‘WOLFSSL_METHOD *’ but argument is of type ‘int’
 1127 | WOLFSSL_ABI WOLFSSL_API WOLFSSL_CTX* wolfSSL_CTX_new(WOLFSSL_METHOD* method);
      |                                                      ~~~~~~~~~~~~~~~~^~~~~~
tests/api.c: In function ‘test_dtls_client_hello_timeout_downgrade’:
tests/api.c:66278:37: error: ‘wolfDTLSv1_2_server_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_server_method’?
66278 |             wolfDTLS_client_method, wolfDTLSv1_2_server_method), 0);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
./tests/unit.h:160:24: note: in definition of macro ‘ExpectInt’
  160 |         int _x = (int)(x);                                                     \
      |                        ^
tests/api.c:66277:9: note: in expansion of macro ‘ExpectIntEQ’
66277 |         ExpectIntEQ(test_memio_setup(&test_ctx, &ctx_c, &ctx_s, &ssl_c, &ssl_s,
      |         ^~~~~~~~~~~
tests/api.c: In function ‘test_dtls_dropped_ccs’:
tests/api.c:66485:9: error: ‘wolfDTLSv1_2_client_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_client_method’?
66485 |         wolfDTLSv1_2_client_method, wolfDTLSv1_2_server_method), 0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
./tests/unit.h:160:24: note: in definition of macro ‘ExpectInt’
  160 |         int _x = (int)(x);                                                     \
      |                        ^
tests/api.c:66484:5: note: in expansion of macro ‘ExpectIntEQ’
66484 |     ExpectIntEQ(test_memio_setup(&test_ctx, &ctx_c, &ctx_s, &ssl_c, &ssl_s,
      |     ^~~~~~~~~~~
tests/api.c:66485:37: error: ‘wolfDTLSv1_2_server_method’ undeclared (first use in this function); did you mean ‘wolfDTLSv1_3_server_method’?
66485 |         wolfDTLSv1_2_client_method, wolfDTLSv1_2_server_method), 0);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
./tests/unit.h:160:24: note: in definition of macro ‘ExpectInt’
  160 |         int _x = (int)(x);                                                     \
      |                        ^
tests/api.c:66484:5: note: in expansion of macro ‘ExpectIntEQ’
66484 |     ExpectIntEQ(test_memio_setup(&test_ctx, &ctx_c, &ctx_s, &ssl_c, &ssl_s,
      |     ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:7608: tests/unit_test-api.o] Error 1
make[2]: Leaving directory '/home/nephele/proj/crazy-network-lib/wolfssl'
make[1]: *** [Makefile:7979: all-recursive] Error 1
make[1]: Leaving directory '/home/nephele/proj/crazy-network-lib/wolfssl'
make: *** [Makefile:4707: all] Error 2
```

**Comment by embhorn** [comment]
Hello @nephele-gh 

I've added a PR to address the build errors you encountered with this configuration. Please note that SCTP is not expected to  work with DTLS1.3. DTLS-SCTP is based on an expired draft RFC.

This issue will be closed automatically when the PR is reviewed and merged.

Thanks,
@embhorn - wolfSSL Support

**Comment by embhorn** [comment]
Hi @nephele-gh 

Thanks for those details. Please send an email to support@wolfssl.com and I can help create a formal feature request for you.

**Comment by ejohnstown** [comment]
When I answered Eric's questions, I was wrong. We supported RFC 6083, but the work we did for that only applies to DTLSv1.2. Our implementation of DTLSv1.3 does not have the SCTP support. While there is a draft RFC, we haven't looked at it and don't have a plan to support it at the moment.
